apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-world-web-deployment
  namespace: cloud-world
  labels:
    app: cloud-world-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-world-web
  template:
    metadata:
      labels:
        app: cloud-world-web
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/r1r3f9h4/cloud-world-ecr/apps:latest
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent