apiVersion: v1
kind: Service
metadata:
  name: cloud-world-web-service
  namespace: cloud-world
  labels:
    app: cloud-world-web
spec:
  type: "LoadBalancer"
  selector:
    app: cloud-world-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80