apiVersion: v1
kind: Service
metadata:
  name: cloud-world-web-service
  namespace: cloud-world
  labels:
    app: cloud-world-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: "LoadBalancer"
  selector:
    app: cloud-world-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080