name: Push Image to AWS ECR Public

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_ecr_public:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"

      - name: Login to AWS ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: |
          docker build -t public.ecr.aws/r1r3f9h4/cloud-world-ecr/apps:latest CloudWorld.Aws.EKS.Web

      - name: Push Docker image to AWS ECR Public
        run: |
          docker push public.ecr.aws/r1r3f9h4/cloud-world-ecr/apps:latest
